[docs]
docdex_url = "https://docs-repository.schlaubi.net"

[inputs]
strings = true
files = true
githubGist = true
pastebin = true
hastebin_urls = ["pasta.with-rice.by.devs-from.asia"]
ghostbin = true
pasty = true
images = true

[auth]
keys = ["apple-is-shit"]
