# This workflow will upload docs to the gh-pages branch whenever something is pushed to master.

name: Docs
on:
  push:
    branches:
      - main

jobs:
  upload_docs:
    name: upload docs
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Publish docs with Gradle
        run: gradle --stacktrace --info clean forp-parser:generateKotlinCommonGrammarSource gitPublishPush
